workflows:
  ios-native-build:
    name: iOS Native App Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "ios_app/GlycoGuide.xcodeproj"
        XCODE_SCHEME: "GlycoGuide"
        BUNDLE_ID: "com.glycoguide.app"
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles --project "$XCODE_PROJECT"
      - name: Build iOS App
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath ios_app/build/GlycoGuide.xcarchive \
            -destination 'generic/platform=iOS' \
            archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath ios_app/build/GlycoGuide.xcarchive \
            -exportPath ios_app/build \
            -exportOptionsPlist ios_app/ExportOptions.plist
    artifacts:
      - ios_app/build/*.ipa
      - ios_app/build/*.xcarchive
    publishing:
      email:
        recipients:
          - support@glycoguide.app
      app_store_connect:
        auth: integration
        submit_to_testflight: true
