workflows:
  ios-native-build:
    name: iOS Native App Build (Manual Signing)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "ios_app/GlycoGuide.xcodeproj"
        XCODE_SCHEME: "GlycoGuide"
        BUNDLE_ID: "com.glycoguide.app"
        TEAM_ID: "9XVR3WAB6Y"
      groups:
        - ios_credentials
    scripts:
      - name: Install Apple certificate
        script: |
          #!/bin/bash
          set -e
          
          # Create a temporary keychain for signing
          KEYCHAIN_PATH="$HOME/Library/Keychains/codemagic.keychain-db"
          KEYCHAIN_PASSWORD="codemagic"
          
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH" || true
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # Decode and import certificate
          echo "$IOS_DISTRIBUTION_CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          security import /tmp/certificate.p12 \
            -P "$IOS_CERTIFICATE_PASSWORD" \
            -A \
            -t cert \
            -f pkcs12 \
            -k "$KEYCHAIN_PATH"
          
          # Allow codesign to access keychain
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # Add keychain to search list
          security list-keychains -d user -s "$KEYCHAIN_PATH" $(security list-keychains -d user | tr -d '"')
          security default-keychain -s "$KEYCHAIN_PATH"
          
          echo "✓ Certificate installed successfully"

      - name: Install provisioning profile
        script: |
          #!/bin/bash
          set -e
          
          # Create profiles directory
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_DIR"
          
          # Decode and install provisioning profile
          echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > "$PROFILES_DIR/GlycoGuide_AppStore.mobileprovision"
          
          # Get profile UUID for reference
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILES_DIR/GlycoGuide_AppStore.mobileprovision"))
          echo "✓ Provisioning profile installed: $PROFILE_UUID"
          
          # Copy with UUID name (required by Xcode)
          cp "$PROFILES_DIR/GlycoGuide_AppStore.mobileprovision" "$PROFILES_DIR/$PROFILE_UUID.mobileprovision"

      - name: Configure Xcode project for manual signing
        script: |
          #!/bin/bash
          set -e
          
          cd ios_app
          
          # Update project.pbxproj for manual signing
          # This sets CODE_SIGN_STYLE to Manual and configures the team
          /usr/libexec/PlistBuddy -c "Set :objects:YOUR_TARGET_ID:buildSettings:CODE_SIGN_STYLE Manual" GlycoGuide.xcodeproj/project.pbxproj 2>/dev/null || true
          
          echo "✓ Xcode project configured for manual signing"

      - name: Build iOS App
        script: |
          #!/bin/bash
          set -e
          
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath ios_app/build/GlycoGuide.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="GlycoGuide_AppStore" \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath ios_app/build/GlycoGuide.xcarchive \
            -exportPath ios_app/build \
            -exportOptionsPlist ios_app/ExportOptions.plist

    artifacts:
      - ios_app/build/*.ipa
      - ios_app/build/*.xcarchive
      - ios_app/build/*.log

    publishing:
      email:
        recipients:
          - support@glycoguide.app
        notify:
          success: true
          failure: true
